{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.service-api.schema-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "mkqhlkollvcibivlothqmoh7iy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.service-api.schema-plugin-1.0.0.jar",
          "url": "laplacian-arch.service-api.schema-plugin-1.0.0.jar",
          "size": 84742,
          "sha512": "aeb222a25238189275cec1977b1559a8cbcdefec3dbaa9abcec5025818480ffa428ae3f0c224889a2434e5f01746055fb9ab72d070236b382e454df12e16857a",
          "sha256": "e44e0a27cdb5db0b830cd2db4ad534924fbcd94e21cad514e22202802d1f601e",
          "sha1": "a83a7f82abfd862e4877494755e700d43f0a7bf1",
          "md5": "88f61e9f8a46fa27c0245a81d4ba34ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian-arch",
          "module": "laplacian-arch.datasource.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.service-api.schema-plugin-1.0.0.jar",
          "url": "laplacian-arch.service-api.schema-plugin-1.0.0.jar",
          "size": 84742,
          "sha512": "aeb222a25238189275cec1977b1559a8cbcdefec3dbaa9abcec5025818480ffa428ae3f0c224889a2434e5f01746055fb9ab72d070236b382e454df12e16857a",
          "sha256": "e44e0a27cdb5db0b830cd2db4ad534924fbcd94e21cad514e22202802d1f601e",
          "sha1": "a83a7f82abfd862e4877494755e700d43f0a7bf1",
          "md5": "88f61e9f8a46fa27c0245a81d4ba34ac"
        }
      ]
    }
  ]
}
