{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.datasource.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "r2xwgg3ifjf5fbkepmpk65w3mm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "size": 45096,
          "sha512": "e4415bc156ad3436abf473aa1ffc7aa63ce107b01f0bdeab957fab69b6924120705ec8d2fd6e1389d9fbda765313cdbf88614a0f4d1430aac09bae5a90973599",
          "sha256": "5063bb26b06537dc590614a67deceda021b447ab7992a43d713f4c3054de1366",
          "sha1": "9a745dde8affa5dc074fb5ec751f1b0a949b0b14",
          "md5": "5cb78e3a37d8a794785b3ddb2d4a7a08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "size": 45096,
          "sha512": "e4415bc156ad3436abf473aa1ffc7aa63ce107b01f0bdeab957fab69b6924120705ec8d2fd6e1389d9fbda765313cdbf88614a0f4d1430aac09bae5a90973599",
          "sha256": "5063bb26b06537dc590614a67deceda021b447ab7992a43d713f4c3054de1366",
          "sha1": "9a745dde8affa5dc074fb5ec751f1b0a949b0b14",
          "md5": "5cb78e3a37d8a794785b3ddb2d4a7a08"
        }
      ]
    }
  ]
}
