{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.datasource.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "d2jrnsm5vraexibd6fqylnw254"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "size": 45154,
          "sha512": "fc8a6437dab82cd2dd70e2bad5d39e6993595f159434373232c060e33ec2f1a03e4bb18e4de33bb2c97246127798eb248e06a7e4160c37816f9a00b7b08c3c67",
          "sha256": "d862efa64b3a6f7de36ebdfe2d8be3333cfb66033a3ec91a63546ab2926a185d",
          "sha1": "3884c458f14f13dc3a26d22dc6d903c32cd7da03",
          "md5": "8508cb5c538f8d33d1630f497f92a958"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "size": 45154,
          "sha512": "fc8a6437dab82cd2dd70e2bad5d39e6993595f159434373232c060e33ec2f1a03e4bb18e4de33bb2c97246127798eb248e06a7e4160c37816f9a00b7b08c3c67",
          "sha256": "d862efa64b3a6f7de36ebdfe2d8be3333cfb66033a3ec91a63546ab2926a185d",
          "sha1": "3884c458f14f13dc3a26d22dc6d903c32cd7da03",
          "md5": "8508cb5c538f8d33d1630f497f92a958"
        }
      ]
    }
  ]
}
