{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.datasource.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "zm7cjf2owbgodiv5jne7csinn4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "size": 45169,
          "sha512": "08c875474b07d6e131e69bd264037d835aeaf8e0b82ae073d2ab9e5dae843a0f1e164ea6bad136877d129a705ae61954551e559c282e1b6f066978ae6bd41e39",
          "sha256": "568771b077e2fb30503fcc643e9efc114e73a5150ee668bc3a19df0514ce48df",
          "sha1": "04d5cb6e387a4158e9e7da7fe493ed55f7e2b4e6",
          "md5": "ff07a7ced9135a1f7a03b36ef82bf01c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.domain-model-plugin-1.0.0.jar",
          "size": 45169,
          "sha512": "08c875474b07d6e131e69bd264037d835aeaf8e0b82ae073d2ab9e5dae843a0f1e164ea6bad136877d129a705ae61954551e559c282e1b6f066978ae6bd41e39",
          "sha256": "568771b077e2fb30503fcc643e9efc114e73a5150ee668bc3a19df0514ce48df",
          "sha1": "04d5cb6e387a4158e9e7da7fe493ed55f7e2b4e6",
          "md5": "ff07a7ced9135a1f7a03b36ef82bf01c"
        }
      ]
    }
  ]
}
