{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.api-service.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "o53ozefz3jbqtlw4rce5jxzs2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "size": 84828,
          "sha512": "29d68a517d045c2af6e18cf6ae25593209a0e94be946ff6c0eeb008e5096c1477da1c1aaf2d8c81e06a68f1d814684faba80460b02203f77cadfaafef517ecc1",
          "sha256": "73daf69f93b38db388f61b24faa8e3a94ec883b7ef66b6d1bfcf4e3751c7b888",
          "sha1": "508e9e602c01a00fc26a0181666c143f4fbee8b2",
          "md5": "61da1edd98c069009a866f287256838a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian-arch",
          "module": "laplacian-arch.datasource.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "size": 84828,
          "sha512": "29d68a517d045c2af6e18cf6ae25593209a0e94be946ff6c0eeb008e5096c1477da1c1aaf2d8c81e06a68f1d814684faba80460b02203f77cadfaafef517ecc1",
          "sha256": "73daf69f93b38db388f61b24faa8e3a94ec883b7ef66b6d1bfcf4e3751c7b888",
          "sha1": "508e9e602c01a00fc26a0181666c143f4fbee8b2",
          "md5": "61da1edd98c069009a866f287256838a"
        }
      ]
    }
  ]
}
