{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.api-service.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "aob7n4hvfza2xphc3ez3epaite"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "size": 493697,
          "sha512": "c97125df4b1c2747d4aa8c8ec3033e17453b7bbb38a0f937cf0934bbf8a58c5913bea2b9260e13ba75f3931888074e56da15a7846ede4e3e8c6ad817c8a5db8f",
          "sha256": "f678d08116813d9d569cd881872e55ab79ea97960d96662667a4b84def6955bd",
          "sha1": "6a6dd32858034cad13baa75092365e11b6bd33ff",
          "md5": "fe05d2eb179051db2cea6195018121e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "size": 493697,
          "sha512": "c97125df4b1c2747d4aa8c8ec3033e17453b7bbb38a0f937cf0934bbf8a58c5913bea2b9260e13ba75f3931888074e56da15a7846ede4e3e8c6ad817c8a5db8f",
          "sha256": "f678d08116813d9d569cd881872e55ab79ea97960d96662667a4b84def6955bd",
          "sha1": "6a6dd32858034cad13baa75092365e11b6bd33ff",
          "md5": "fe05d2eb179051db2cea6195018121e3"
        }
      ]
    }
  ]
}
