{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.api-service.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "kobgx3frzjcvrlfkqocrkoapwm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "size": 263370,
          "sha512": "12cef822914e929ab3935fa6014fcd22979134d7d17bf95c4bae0d063a5a61f3e1932ab310b627ee9043f1aae1348d18a17d08e6e92eac6de7c97bb79b70600b",
          "sha256": "2e509a4f66cc145a699756de8bd0dd20d1cf715f3526bed6002b267ec6848f8f",
          "sha1": "20e353107efe1e246ce2e93198aef9214f4d0296",
          "md5": "4fd7ba818f3a46610c859372fefd0ea8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.api-service.domain-model-plugin-1.0.0.jar",
          "size": 263370,
          "sha512": "12cef822914e929ab3935fa6014fcd22979134d7d17bf95c4bae0d063a5a61f3e1932ab310b627ee9043f1aae1348d18a17d08e6e92eac6de7c97bb79b70600b",
          "sha256": "2e509a4f66cc145a699756de8bd0dd20d1cf715f3526bed6002b267ec6848f8f",
          "sha1": "20e353107efe1e246ce2e93198aef9214f4d0296",
          "md5": "4fd7ba818f3a46610c859372fefd0ea8"
        }
      ]
    }
  ]
}
