{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.schema.metamodel",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "xl5yzs3xljc2hohvmqmatoeecy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.schema.metamodel-1.0.0.jar",
          "url": "laplacian.schema.metamodel-1.0.0.jar",
          "size": 109483,
          "sha512": "d08f6326618a3906a6234a6d4adedda91d1ea4e4d6c84a201497320c65324f4c99d9101d1e6a775b9fec50192f1de047fea50043e301d72b972093d98a9988f2",
          "sha256": "c00c2ad234724f969209abe62914a44ecfa3861de1bac5d4d4a9e4a2afd38730",
          "sha1": "1e84973bd3b52885ba59725ffcf69ad29ff0ad39",
          "md5": "589015b6dbaa9706a80b0548f1820aad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.schema.metamodel-1.0.0.jar",
          "url": "laplacian.schema.metamodel-1.0.0.jar",
          "size": 109483,
          "sha512": "d08f6326618a3906a6234a6d4adedda91d1ea4e4d6c84a201497320c65324f4c99d9101d1e6a775b9fec50192f1de047fea50043e301d72b972093d98a9988f2",
          "sha256": "c00c2ad234724f969209abe62914a44ecfa3861de1bac5d4d4a9e4a2afd38730",
          "sha1": "1e84973bd3b52885ba59725ffcf69ad29ff0ad39",
          "md5": "589015b6dbaa9706a80b0548f1820aad"
        }
      ]
    }
  ]
}
