{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.schema.metamodel",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "ucylbgsctzhjbhyec7btee7euq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.schema.metamodel-1.0.0.jar",
          "url": "laplacian.schema.metamodel-1.0.0.jar",
          "size": 109499,
          "sha512": "288147e43ecc66d7c99dca9f63e53f09ea4fb6176f270dd991ce0e50522f6526e43e0377c5998808cc1bc722a53546e9c0359b26af0397023c760d125ec08291",
          "sha256": "d0b72fc4c96b948e07316212ec0ebc6279b1e17aa2e20273a59cfdc0ee72cc79",
          "sha1": "1e91a08dfb68fa2dc4515999cf64e35d1d1a78fc",
          "md5": "7f847152cba86c4db8fd89ee371c881b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.schema.metamodel",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.schema.project",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.schema.metamodel-1.0.0.jar",
          "url": "laplacian.schema.metamodel-1.0.0.jar",
          "size": 109499,
          "sha512": "288147e43ecc66d7c99dca9f63e53f09ea4fb6176f270dd991ce0e50522f6526e43e0377c5998808cc1bc722a53546e9c0359b26af0397023c760d125ec08291",
          "sha256": "d0b72fc4c96b948e07316212ec0ebc6279b1e17aa2e20273a59cfdc0ee72cc79",
          "sha1": "1e91a08dfb68fa2dc4515999cf64e35d1d1a78fc",
          "md5": "7f847152cba86c4db8fd89ee371c881b"
        }
      ]
    }
  ]
}
