{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.datasource.schema-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "mkcwwn2kwfh27bknr55dkb5jhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "size": 45035,
          "sha512": "9827da87eb175249e71a623a5414a59bbd642bc8b03a969ecde08228900f995e787c6a752a3de019d04db10fdf4cd5d259b497892f8bd28d72f6fe65ec49b8df",
          "sha256": "a0a23cdda4212dc59eadfb23648c35eecb30b920e7d9de187f817bd0c19fda80",
          "sha1": "a4016868fba57aeba2e9f2787f3bdc4cac89be5c",
          "md5": "f407d3d536f5867713735ff989778c01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "size": 45035,
          "sha512": "9827da87eb175249e71a623a5414a59bbd642bc8b03a969ecde08228900f995e787c6a752a3de019d04db10fdf4cd5d259b497892f8bd28d72f6fe65ec49b8df",
          "sha256": "a0a23cdda4212dc59eadfb23648c35eecb30b920e7d9de187f817bd0c19fda80",
          "sha1": "a4016868fba57aeba2e9f2787f3bdc4cac89be5c",
          "md5": "f407d3d536f5867713735ff989778c01"
        }
      ]
    }
  ]
}
