{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.datasource.schema-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "qjelou7k45brhc4whhasrmhr5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "size": 45035,
          "sha512": "729ede33330991370a0f411ee4d2ab80ffd7a891b12a28367b0a8acced87f478d7bede9bbd0ad2bea99c5de2837e2ac22c96397e2bf7919245b1fe30497ba776",
          "sha256": "8b656f33dac2792bf2f235c5a0d978704204d70e8f5e0924e7fc73ecbb108f58",
          "sha1": "9a2cc94429e4c8bc744be1d323fc9748120000db",
          "md5": "a2ea9ac0339b85a3e78fbfccf6198bc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "url": "laplacian-arch.datasource.schema-plugin-1.0.0.jar",
          "size": 45035,
          "sha512": "729ede33330991370a0f411ee4d2ab80ffd7a891b12a28367b0a8acced87f478d7bede9bbd0ad2bea99c5de2837e2ac22c96397e2bf7919245b1fe30497ba776",
          "sha256": "8b656f33dac2792bf2f235c5a0d978704204d70e8f5e0924e7fc73ecbb108f58",
          "sha1": "9a2cc94429e4c8bc744be1d323fc9748120000db",
          "md5": "a2ea9ac0339b85a3e78fbfccf6198bc7"
        }
      ]
    }
  ]
}
