{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.schema.project",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "eq3wm6i665c7bncbdsmpjzelca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.schema.project-1.0.0.jar",
          "url": "laplacian.schema.project-1.0.0.jar",
          "size": 36379,
          "sha512": "68cfa9d42cc0a91c2e1f285b2198d54a3cfc264e985ce24e6e813e400df721d39fb133ff5779e44105bf1a6c62ce4233baaeec50a2afef50e80882c2d60d4619",
          "sha256": "58a5e79f42d9ba3a23b651287b592420991c0cd381f57c5e9b3aa1fd4e1693f5",
          "sha1": "1863b64bdda838dfb9e08402b905e49ae607b2ec",
          "md5": "8efbcc5c298842342bd1d6ca85c79753"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.schema.project-1.0.0.jar",
          "url": "laplacian.schema.project-1.0.0.jar",
          "size": 36379,
          "sha512": "68cfa9d42cc0a91c2e1f285b2198d54a3cfc264e985ce24e6e813e400df721d39fb133ff5779e44105bf1a6c62ce4233baaeec50a2afef50e80882c2d60d4619",
          "sha256": "58a5e79f42d9ba3a23b651287b592420991c0cd381f57c5e9b3aa1fd4e1693f5",
          "sha1": "1863b64bdda838dfb9e08402b905e49ae607b2ec",
          "md5": "8efbcc5c298842342bd1d6ca85c79753"
        }
      ]
    }
  ]
}
