{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.schema.project",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2aaggvunhzhpxl2fvgzj4kubuy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.schema.project-1.0.0.jar",
          "url": "laplacian.schema.project-1.0.0.jar",
          "size": 36918,
          "sha512": "38b8c4c30fe075235f72190246c7a869b9ded8ed7cf1155719ef2dc1070339a4c7413947af60314bbbbcbaf7368aeefcd1a63aabfc0b021e2d83cc544e4cd848",
          "sha256": "da558c133b5376851a69e23d0f4cf3c9f87ecaa2fa382d959199c141cd05a1b6",
          "sha1": "be9432c75701b0d90376917bc304d98d0a5e55ef",
          "md5": "8a5bb0ad959b46501f990d63c281e797"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.schema.project-1.0.0.jar",
          "url": "laplacian.schema.project-1.0.0.jar",
          "size": 36918,
          "sha512": "38b8c4c30fe075235f72190246c7a869b9ded8ed7cf1155719ef2dc1070339a4c7413947af60314bbbbcbaf7368aeefcd1a63aabfc0b021e2d83cc544e4cd848",
          "sha256": "da558c133b5376851a69e23d0f4cf3c9f87ecaa2fa382d959199c141cd05a1b6",
          "sha1": "be9432c75701b0d90376917bc304d98d0a5e55ef",
          "md5": "8a5bb0ad959b46501f990d63c281e797"
        }
      ]
    }
  ]
}
