{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.project.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "zwdp4pgds5dxzeckw2at35oxhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "url": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "size": 108494,
          "sha512": "f9846a1bec427f9f2b4db0bedd28c79c6e94db3eb2b157aca11ecab88c658fb204f3c2aa76a9b97a2f84aa5a86af5a8207bb2fb6f0ad05d853ab209991e343dd",
          "sha256": "27c4872978cb01f5e1607cb33d17388edd63649b35969c8f806f8618bad02bf6",
          "sha1": "73f3d6b95c1cf86417942ca9dde8c8223ed95f98",
          "md5": "1a33842ce14c7d03553e07e9f1f2ceeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "url": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "size": 108494,
          "sha512": "f9846a1bec427f9f2b4db0bedd28c79c6e94db3eb2b157aca11ecab88c658fb204f3c2aa76a9b97a2f84aa5a86af5a8207bb2fb6f0ad05d853ab209991e343dd",
          "sha256": "27c4872978cb01f5e1607cb33d17388edd63649b35969c8f806f8618bad02bf6",
          "sha1": "73f3d6b95c1cf86417942ca9dde8c8223ed95f98",
          "md5": "1a33842ce14c7d03553e07e9f1f2ceeb"
        }
      ]
    }
  ]
}
