{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.project.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "kpep5xhl55dqdb3yyvw4ocu2x4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "url": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "size": 94202,
          "sha512": "142819c93d3d7e3650b49fa6f5e736cf54960138c8cf9302e13e57746ba6a8fd2c18bde4ff68615054e11d080fb74ff39f9ae043361289e2cf2a8f0e5e3a0648",
          "sha256": "1385ae39345dc54a120a58d673528cbe4158e15fea1852f94ba8daddb532695f",
          "sha1": "087c701a308a61b46e47eac88df3521360e2a460",
          "md5": "a1e132e044c9a2652f3f724b90f5d2ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "url": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "size": 94202,
          "sha512": "142819c93d3d7e3650b49fa6f5e736cf54960138c8cf9302e13e57746ba6a8fd2c18bde4ff68615054e11d080fb74ff39f9ae043361289e2cf2a8f0e5e3a0648",
          "sha256": "1385ae39345dc54a120a58d673528cbe4158e15fea1852f94ba8daddb532695f",
          "sha1": "087c701a308a61b46e47eac88df3521360e2a460",
          "md5": "a1e132e044c9a2652f3f724b90f5d2ba"
        }
      ]
    }
  ]
}
