{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.project.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "uc26qsfnabhkjhtkrxdesoxlzi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "url": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "size": 94202,
          "sha512": "45161c2e7cb6fe2305bb8af42fa34412c9379662f10bbd1f072f3ae4a8616de600e8ad2aa76b9fccdf0e4bbfc9edcb5e9316c98ebae72976b65bdffb585a12a7",
          "sha256": "18bbdd56a39f57583b5efecac4d996a2a40d740df1678966ec73e435d0c74ce0",
          "sha1": "f6db53fcdb74fe25b2af3561a18e4f89f8e31ace",
          "md5": "fe71fb23c9e40be45d9eeb3a34f51360"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "url": "laplacian.project.domain-model-plugin-1.0.0.jar",
          "size": 94202,
          "sha512": "45161c2e7cb6fe2305bb8af42fa34412c9379662f10bbd1f072f3ae4a8616de600e8ad2aa76b9fccdf0e4bbfc9edcb5e9316c98ebae72976b65bdffb585a12a7",
          "sha256": "18bbdd56a39f57583b5efecac4d996a2a40d740df1678966ec73e435d0c74ce0",
          "sha1": "f6db53fcdb74fe25b2af3561a18e4f89f8e31ace",
          "md5": "fe71fb23c9e40be45d9eeb3a34f51360"
        }
      ]
    }
  ]
}
