{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.service-api.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "qbrfk3mq5jcdlh22ljdluqsrye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.service-api.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.service-api.domain-model-plugin-1.0.0.jar",
          "size": 84893,
          "sha512": "8000f269b77b119007d26c237b2fc880aa50c2498b51f3943f1e3858fe52b3716a267339eafcddb5a5b49618d798ada3bfbba0c2ff4d0beb24508e085664f16a",
          "sha256": "5f01f874071abada9f3346110025fcb17fd27cf3b1b75956797609bf1e318d66",
          "sha1": "d85abbe9c2b4e82870b111759acfb4865fe25c8c",
          "md5": "02986ed3cc2714f38ebb9282b957cc1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian-arch",
          "module": "laplacian-arch.datasource.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.service-api.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.service-api.domain-model-plugin-1.0.0.jar",
          "size": 84893,
          "sha512": "8000f269b77b119007d26c237b2fc880aa50c2498b51f3943f1e3858fe52b3716a267339eafcddb5a5b49618d798ada3bfbba0c2ff4d0beb24508e085664f16a",
          "sha256": "5f01f874071abada9f3346110025fcb17fd27cf3b1b75956797609bf1e318d66",
          "sha1": "d85abbe9c2b4e82870b111759acfb4865fe25c8c",
          "md5": "02986ed3cc2714f38ebb9282b957cc1f"
        }
      ]
    }
  ]
}
