{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.metamodel-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "ypfka3rnhjhqtig3zg6t3y3zwi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.metamodel-plugin-1.0.0.jar",
          "url": "laplacian.metamodel-plugin-1.0.0.jar",
          "size": 109483,
          "sha512": "39897a8352028b3ce55b87d4baae25b2fc912212842b1e931f3351d74d2817f10eee367912eee9706ab14ddfbced9bd89aeaca692057a9152b3808e314c795bc",
          "sha256": "e698e001eae147d5a54b5c7c5fbc2500713c8ff17b6274cc51221671496aac66",
          "sha1": "fc53f02c77c08f5e1d9f1e98240dccdcc7ce77df",
          "md5": "072a5b1e41e16b5936307e175d540173"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.metamodel-plugin-1.0.0.jar",
          "url": "laplacian.metamodel-plugin-1.0.0.jar",
          "size": 109483,
          "sha512": "39897a8352028b3ce55b87d4baae25b2fc912212842b1e931f3351d74d2817f10eee367912eee9706ab14ddfbced9bd89aeaca692057a9152b3808e314c795bc",
          "sha256": "e698e001eae147d5a54b5c7c5fbc2500713c8ff17b6274cc51221671496aac66",
          "sha1": "fc53f02c77c08f5e1d9f1e98240dccdcc7ce77df",
          "md5": "072a5b1e41e16b5936307e175d540173"
        }
      ]
    }
  ]
}
