{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.metamodel-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ft34cxxbmnegpj4gxbuaz6dptm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.metamodel-plugin-1.0.0.jar",
          "url": "laplacian.metamodel-plugin-1.0.0.jar",
          "size": 140833,
          "sha512": "6697109ea7e738aab8844c5408ed57ad95ddffe4f62ddc907fae9da7e1076017395d438866d789fb3d522efdd42a1bd122e3fa2aa5eb46079bee8285f3bd7d47",
          "sha256": "eeb9c7ca7490be6f8a0a3fed49457ea93c2eec98620cffd5395524bef53a61db",
          "sha1": "1387844ddee50813d7fb435537e849ac7fdec590",
          "md5": "3047325bc8dfc0395faf8b94a595f05b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.metamodel-plugin-1.0.0.jar",
          "url": "laplacian.metamodel-plugin-1.0.0.jar",
          "size": 140833,
          "sha512": "6697109ea7e738aab8844c5408ed57ad95ddffe4f62ddc907fae9da7e1076017395d438866d789fb3d522efdd42a1bd122e3fa2aa5eb46079bee8285f3bd7d47",
          "sha256": "eeb9c7ca7490be6f8a0a3fed49457ea93c2eec98620cffd5395524bef53a61db",
          "sha1": "1387844ddee50813d7fb435537e849ac7fdec590",
          "md5": "3047325bc8dfc0395faf8b94a595f05b"
        }
      ]
    }
  ]
}
