{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.metamodel-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "zwlk6b2x7bbmzbcqfl4ch4pgze"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.metamodel-plugin-1.0.0.jar",
          "url": "laplacian.metamodel-plugin-1.0.0.jar",
          "size": 96582,
          "sha512": "31890dfdc8e32d28fce6fa88b1f5f59ddf7d5a3b4542a6da9bcc5ba0da2c981eacd06acee398a398de71c9e51c1429404f82d14d4ae3bc60c5197db477d09441",
          "sha256": "fc33bddc383364c38943e431746ca9f82be576a219a36db89176f162c662dce4",
          "sha1": "cfcd994d49e2e40eae8eb5228118cc28dce0ece8",
          "md5": "daa5b3a0b5c9d34843866af7d72b6c88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.metamodel-plugin-1.0.0.jar",
          "url": "laplacian.metamodel-plugin-1.0.0.jar",
          "size": 96582,
          "sha512": "31890dfdc8e32d28fce6fa88b1f5f59ddf7d5a3b4542a6da9bcc5ba0da2c981eacd06acee398a398de71c9e51c1429404f82d14d4ae3bc60c5197db477d09441",
          "sha256": "fc33bddc383364c38943e431746ca9f82be576a219a36db89176f162c662dce4",
          "sha1": "cfcd994d49e2e40eae8eb5228118cc28dce0ece8",
          "md5": "daa5b3a0b5c9d34843866af7d72b6c88"
        }
      ]
    }
  ]
}
