{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.schema.service-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jbsewdmemnal7ggwoourtarkoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.schema.service-api-1.0.0.jar",
          "url": "laplacian-arch.schema.service-api-1.0.0.jar",
          "size": 84571,
          "sha512": "0a81b3605759447dff7e37e3aeafc58291a16c9629169140792f9f48ea2ef8c778571c65500710819ce0381c1f21d5023cad64a7638a129afbb8b4f05eb84a4e",
          "sha256": "c80318107e8da740bbb34b4f9941c6fda2dfc3093c3c583aa2ab726f8e9a24b9",
          "sha1": "4b3ba48762bc33b6fd2c62990527049aa2f1de21",
          "md5": "dba07030f809a48760d8c95d12f40306"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.schema.metamodel",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.schema.project",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian-arch",
          "module": "laplacian-arch.schema.datasource",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.schema.service-api-1.0.0.jar",
          "url": "laplacian-arch.schema.service-api-1.0.0.jar",
          "size": 84571,
          "sha512": "0a81b3605759447dff7e37e3aeafc58291a16c9629169140792f9f48ea2ef8c778571c65500710819ce0381c1f21d5023cad64a7638a129afbb8b4f05eb84a4e",
          "sha256": "c80318107e8da740bbb34b4f9941c6fda2dfc3093c3c583aa2ab726f8e9a24b9",
          "sha1": "4b3ba48762bc33b6fd2c62990527049aa2f1de21",
          "md5": "dba07030f809a48760d8c95d12f40306"
        }
      ]
    }
  ]
}
