{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.project.schema-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "qxuoolnv5vbjddi24oukk25gle"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.project.schema-plugin-1.0.0.jar",
          "url": "laplacian.project.schema-plugin-1.0.0.jar",
          "size": 55926,
          "sha512": "11c71b3781d83476c166bfc6df85aa29aeea6f3249fdd57aab17abb80eae89cef45e957eda1b75dc1a452fc51a838e199060ac1fedaa3fd857650ed2cad47ab4",
          "sha256": "e84484feb2b3a092dbb225d783bfcc92ea133f675da237d6b24c0ce7f7b774e5",
          "sha1": "689c5a2db8c4ff15043fd94730e0b639ed467ec0",
          "md5": "b6f29b8d4efb4f0c5f836e223f9c907d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.project.schema-plugin-1.0.0.jar",
          "url": "laplacian.project.schema-plugin-1.0.0.jar",
          "size": 55926,
          "sha512": "11c71b3781d83476c166bfc6df85aa29aeea6f3249fdd57aab17abb80eae89cef45e957eda1b75dc1a452fc51a838e199060ac1fedaa3fd857650ed2cad47ab4",
          "sha256": "e84484feb2b3a092dbb225d783bfcc92ea133f675da237d6b24c0ce7f7b774e5",
          "sha1": "689c5a2db8c4ff15043fd94730e0b639ed467ec0",
          "md5": "b6f29b8d4efb4f0c5f836e223f9c907d"
        }
      ]
    }
  ]
}
