{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.project.schema-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "c7cg2ltknjh6tok5evc2gpztg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.project.schema-plugin-1.0.0.jar",
          "url": "laplacian.project.schema-plugin-1.0.0.jar",
          "size": 71246,
          "sha512": "c137f6ea0110fe785849778a2cddc41851adbefa09c3de4981cfccb0698b11708f8c357f5e257531dc914ca47da1d49ce069a678e0ebf27473d6df17a3e7d0d7",
          "sha256": "1f96dc051bb8151f0202816f4f8e26d5f416160ffb55ca339520de2f09a89d22",
          "sha1": "23e0fdb4110f84bb397dd411ef4938d5ad6bc57c",
          "md5": "49b0020c0b1100aed1f9fb922792b6c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.project.schema-plugin-1.0.0.jar",
          "url": "laplacian.project.schema-plugin-1.0.0.jar",
          "size": 71246,
          "sha512": "c137f6ea0110fe785849778a2cddc41851adbefa09c3de4981cfccb0698b11708f8c357f5e257531dc914ca47da1d49ce069a678e0ebf27473d6df17a3e7d0d7",
          "sha256": "1f96dc051bb8151f0202816f4f8e26d5f416160ffb55ca339520de2f09a89d22",
          "sha1": "23e0fdb4110f84bb397dd411ef4938d5ad6bc57c",
          "md5": "49b0020c0b1100aed1f9fb922792b6c3"
        }
      ]
    }
  ]
}
