{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.project.schema-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "ki73zlog55cclpoh7hp24ozhs4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.project.schema-plugin-1.0.0.jar",
          "url": "laplacian.project.schema-plugin-1.0.0.jar",
          "size": 94031,
          "sha512": "89fec437b6b63815a4f0327714d5dd964acea77d4d71751bfc412a0ca4024e938465ff58b9dbdfba71289742ce7d1d18712c3de0a59b046ff7c4617f71e26b51",
          "sha256": "07770048bd9869a1e91e38b0f3d8287c1f9e5a7372837d876601bbf9349764ee",
          "sha1": "824f83607e70f986f7d2445091ba3e5258ae9421",
          "md5": "d3d2cf902f4bb82d233362c2f79d5d1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.project.schema-plugin-1.0.0.jar",
          "url": "laplacian.project.schema-plugin-1.0.0.jar",
          "size": 94031,
          "sha512": "89fec437b6b63815a4f0327714d5dd964acea77d4d71751bfc412a0ca4024e938465ff58b9dbdfba71289742ce7d1d18712c3de0a59b046ff7c4617f71e26b51",
          "sha256": "07770048bd9869a1e91e38b0f3d8287c1f9e5a7372837d876601bbf9349764ee",
          "sha1": "824f83607e70f986f7d2445091ba3e5258ae9421",
          "md5": "d3d2cf902f4bb82d233362c2f79d5d1c"
        }
      ]
    }
  ]
}
