{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.deployment.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "7nnxksf7sbg4fafaibdqripupq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "size": 280783,
          "sha512": "9fb7957cf238b5b73d975e346096ab93e23c9b82a5ae1e9ddbccc053b412a5b81a543e7dc81d043583b44d64f7b3272e5484eb26c7db175c7bbf5135c1e4f87a",
          "sha256": "de712b6c3809ef7386bf06c922c1a9008778b80c65be607291959654141e4012",
          "sha1": "de78498e9ad13828ea88f1658e6653caf38be273",
          "md5": "a8e2ac6511dfd49d5943b00ffce6fdbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian-arch",
          "module": "laplacian-arch.api-service.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "size": 280783,
          "sha512": "9fb7957cf238b5b73d975e346096ab93e23c9b82a5ae1e9ddbccc053b412a5b81a543e7dc81d043583b44d64f7b3272e5484eb26c7db175c7bbf5135c1e4f87a",
          "sha256": "de712b6c3809ef7386bf06c922c1a9008778b80c65be607291959654141e4012",
          "sha1": "de78498e9ad13828ea88f1658e6653caf38be273",
          "md5": "a8e2ac6511dfd49d5943b00ffce6fdbd"
        }
      ]
    }
  ]
}
