{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.deployment.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "cfncf37lvrcc5hj7vdq5ac65ze"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "size": 199999,
          "sha512": "c2bcef34b64a8c3b3ee8a9fb12545fa4a8017954c6c4164b1d81685b5ded32e2893d7a0ef8fd110d72c677aab4e9cb26a0147ea7d39098ab818985f46e5647a3",
          "sha256": "6d06d9fd8734c0462a23a32750910b9bbea4c603a3c112cef5784f0b01472f9a",
          "sha1": "8c1a81a847f50503aa07da2db182794d108f7273",
          "md5": "1441061eff0a41ea99954d61437a3a70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian-arch",
          "module": "laplacian-arch.api-service.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "size": 199999,
          "sha512": "c2bcef34b64a8c3b3ee8a9fb12545fa4a8017954c6c4164b1d81685b5ded32e2893d7a0ef8fd110d72c677aab4e9cb26a0147ea7d39098ab818985f46e5647a3",
          "sha256": "6d06d9fd8734c0462a23a32750910b9bbea4c603a3c112cef5784f0b01472f9a",
          "sha1": "8c1a81a847f50503aa07da2db182794d108f7273",
          "md5": "1441061eff0a41ea99954d61437a3a70"
        }
      ]
    }
  ]
}
