{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian-arch",
    "module": "laplacian-arch.deployment.domain-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "godnj63d6fblzfyybqtweb5wqy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "size": 119421,
          "sha512": "5ed295063794ef20a6343876fe9edf5840271be6d4e00d66d61d5497849362253a6fdad3b139c7b3fc142f729fe4ab1f00730f2bcc0e71bcdfea24b6ebe2c92e",
          "sha256": "2c23b5509a6d990a48f6636dd9a5cc94a0d064bccfad7b16cfc1a31c15f5cded",
          "sha1": "3f0b62babd9a9699afe21eb06b585ad9ee0ac57a",
          "md5": "2b9fa7366e68331c9d01f83b47078512"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian-arch",
          "module": "laplacian-arch.api-service.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "url": "laplacian-arch.deployment.domain-model-plugin-1.0.0.jar",
          "size": 119421,
          "sha512": "5ed295063794ef20a6343876fe9edf5840271be6d4e00d66d61d5497849362253a6fdad3b139c7b3fc142f729fe4ab1f00730f2bcc0e71bcdfea24b6ebe2c92e",
          "sha256": "2c23b5509a6d990a48f6636dd9a5cc94a0d064bccfad7b16cfc1a31c15f5cded",
          "sha1": "3f0b62babd9a9699afe21eb06b585ad9ee0ac57a",
          "md5": "2b9fa7366e68331c9d01f83b47078512"
        }
      ]
    }
  ]
}
