{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.common-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "bumqz25wtnhk5nju2tzuamswbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.common-model-plugin-1.0.0.jar",
          "url": "laplacian.common-model-plugin-1.0.0.jar",
          "size": 59852,
          "sha512": "d1a47beec5802d73640d1fed8d15545a6b818756fd90bb11ea98278f1d7f467d4d9f8b12580d1791e02d1a62a834b8c1155feacee0da89990adf3df2d7ae08a0",
          "sha256": "7b6c11f7d43365f006c9c48d7e6bc1541333fdf46edb0a7b9d93ebed65da1022",
          "sha1": "cb4c5b6c0b0648f2f42b758b7b5a6ca62337f8a6",
          "md5": "e570fa538a3a841929b7a98ebb377c8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.common-model-plugin-1.0.0.jar",
          "url": "laplacian.common-model-plugin-1.0.0.jar",
          "size": 59852,
          "sha512": "d1a47beec5802d73640d1fed8d15545a6b818756fd90bb11ea98278f1d7f467d4d9f8b12580d1791e02d1a62a834b8c1155feacee0da89990adf3df2d7ae08a0",
          "sha256": "7b6c11f7d43365f006c9c48d7e6bc1541333fdf46edb0a7b9d93ebed65da1022",
          "sha1": "cb4c5b6c0b0648f2f42b758b7b5a6ca62337f8a6",
          "md5": "e570fa538a3a841929b7a98ebb377c8e"
        }
      ]
    }
  ]
}
