{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.common-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "oa7m6v7iljfrfp6bt4az3zugia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.common-model-plugin-1.0.0.jar",
          "url": "laplacian.common-model-plugin-1.0.0.jar",
          "size": 59913,
          "sha512": "d871bf17aa25856121bbb8a5f9a531f9e9624fac4d06127ffa0da2fdf9fd8700b7463cda720d58109282c3b0563854f7e56f6215118fc2ad21648cf6eaa2f73f",
          "sha256": "0c1c088dc2f007001bb6bb2bfd76353b709a646bf1692ff91b72d198ac5b2cb5",
          "sha1": "941c9d7a43cb9a228a6b05787133d0846c47c327",
          "md5": "8130935d861a5060af3fc6a454151c7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.schema-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.common-model-plugin-1.0.0.jar",
          "url": "laplacian.common-model-plugin-1.0.0.jar",
          "size": 59913,
          "sha512": "d871bf17aa25856121bbb8a5f9a531f9e9624fac4d06127ffa0da2fdf9fd8700b7463cda720d58109282c3b0563854f7e56f6215118fc2ad21648cf6eaa2f73f",
          "sha256": "0c1c088dc2f007001bb6bb2bfd76353b709a646bf1692ff91b72d198ac5b2cb5",
          "sha1": "941c9d7a43cb9a228a6b05787133d0846c47c327",
          "md5": "8130935d861a5060af3fc6a454151c7d"
        }
      ]
    }
  ]
}
