{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.common-model-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "inopcfgjvrftdiph6w36dmjb3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "laplacian.common-model-plugin-1.0.0.jar",
          "url": "laplacian.common-model-plugin-1.0.0.jar",
          "size": 59477,
          "sha512": "7e0cb71bf75df4da101bbb45439f57f952fea3a5871729b8fafba4332dbd8e3b33f1f39e315be12bc112f75c217aa0056c86b204d56ebf792fd9be791da94771",
          "sha256": "c6ca346510c7f72bb8c3db3e15d5d9e9543d569f3ab387313142b4e8c3604d57",
          "sha1": "e7827611065a760a919c3fc10f6bdcaedf315bfc",
          "md5": "4cfb34e91ad8aabaf0234f71896671df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.generator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.metamodel-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.project.domain-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "laplacian",
          "module": "laplacian.common-model-plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.common-model-plugin-1.0.0.jar",
          "url": "laplacian.common-model-plugin-1.0.0.jar",
          "size": 59477,
          "sha512": "7e0cb71bf75df4da101bbb45439f57f952fea3a5871729b8fafba4332dbd8e3b33f1f39e315be12bc112f75c217aa0056c86b204d56ebf792fd9be791da94771",
          "sha256": "c6ca346510c7f72bb8c3db3e15d5d9e9543d569f3ab387313142b4e8c3604d57",
          "sha1": "e7827611065a760a919c3fc10f6bdcaedf315bfc",
          "md5": "4cfb34e91ad8aabaf0234f71896671df"
        }
      ]
    }
  ]
}
