{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.generator",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xwlkbfov35hqbmlgckv3nvmtqy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.generator-1.0.0.jar",
          "url": "laplacian.generator-1.0.0.jar",
          "size": 244550,
          "sha512": "7ef1c18d607b8cdf2f1a24b0da6d559a6d656029ac1ef65427a1821a0dd29291704539b8fde99d467ab7979a3a354246731f786f6406d3583c4dc6b8b0a13cd0",
          "sha256": "2e835a08bf9558012fa8f0dbb57c543ee00b4687e64d5aaa6f3fb4a206ccdb8c",
          "sha1": "79fb10dd0c80abdec94a84b69dd6e2573fb18812",
          "md5": "4e0dcee3b54785d1fbbfa7e32ed0638c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "org.atteo",
          "module": "evo-inflector",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml",
          "version": {
            "requires": "1.2020.20"
          }
        },
        {
          "group": "com.github.javafaker",
          "module": "javafaker",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.generator-1.0.0.jar",
          "url": "laplacian.generator-1.0.0.jar",
          "size": 244550,
          "sha512": "7ef1c18d607b8cdf2f1a24b0da6d559a6d656029ac1ef65427a1821a0dd29291704539b8fde99d467ab7979a3a354246731f786f6406d3583c4dc6b8b0a13cd0",
          "sha256": "2e835a08bf9558012fa8f0dbb57c543ee00b4687e64d5aaa6f3fb4a206ccdb8c",
          "sha1": "79fb10dd0c80abdec94a84b69dd6e2573fb18812",
          "md5": "4e0dcee3b54785d1fbbfa7e32ed0638c"
        }
      ]
    }
  ]
}
