{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.generator",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "wnwbrjndcffvfos3jszokmbdfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.generator-1.0.0.jar",
          "url": "laplacian.generator-1.0.0.jar",
          "size": 238635,
          "sha512": "882ab6e3259905664ed07ad1316d076e38faac101afc0f191d7332a0bbcf4f87eba2f42eaa82960b394edd2a5a9a4da45c41258eaa62f899beb2884326146457",
          "sha256": "a4e855a6aa4c49e025922084dd43d5b9a1e9ae7f152f02dadc7414e3a239ce69",
          "sha1": "9b7d6e15704c308b6203ba9f74940e58b068d07a",
          "md5": "a8246d56681bee74bfa4858a4842b3a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "org.atteo",
          "module": "evo-inflector",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml",
          "version": {
            "requires": "1.2019.5"
          }
        },
        {
          "group": "com.github.javafaker",
          "module": "javafaker",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.generator-1.0.0.jar",
          "url": "laplacian.generator-1.0.0.jar",
          "size": 238635,
          "sha512": "882ab6e3259905664ed07ad1316d076e38faac101afc0f191d7332a0bbcf4f87eba2f42eaa82960b394edd2a5a9a4da45c41258eaa62f899beb2884326146457",
          "sha256": "a4e855a6aa4c49e025922084dd43d5b9a1e9ae7f152f02dadc7414e3a239ce69",
          "sha1": "9b7d6e15704c308b6203ba9f74940e58b068d07a",
          "md5": "a8246d56681bee74bfa4858a4842b3a2"
        }
      ]
    }
  ]
}
