{
  "formatVersion": "1.1",
  "component": {
    "group": "laplacian",
    "module": "laplacian.generator",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "uddrvislhncplaui4st2zjt6f4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.generator-1.0.0.jar",
          "url": "laplacian.generator-1.0.0.jar",
          "size": 211249,
          "sha512": "aa048e57ae6ab074380b6285a4173ec1f2aa91a8e6ebcd9adccdc7c0c4a0142c5cce707335d7d07a9f67557a046d17ac0093b62c6428a67e5a1ae0822a0ec575",
          "sha256": "2e87f6822dfb4479420d1d1ee7afd743a4679135046416c88c104adee5711333",
          "sha1": "f80176ceec788a828105fea41627a5fd75fb99b6",
          "md5": "7625e0d608641bef0bef663ca181b38f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "org.atteo",
          "module": "evo-inflector",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml",
          "version": {
            "requires": "1.2019.5"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "laplacian.generator-1.0.0.jar",
          "url": "laplacian.generator-1.0.0.jar",
          "size": 211249,
          "sha512": "aa048e57ae6ab074380b6285a4173ec1f2aa91a8e6ebcd9adccdc7c0c4a0142c5cce707335d7d07a9f67557a046d17ac0093b62c6428a67e5a1ae0822a0ec575",
          "sha256": "2e87f6822dfb4479420d1d1ee7afd743a4679135046416c88c104adee5711333",
          "sha1": "f80176ceec788a828105fea41627a5fd75fb99b6",
          "md5": "7625e0d608641bef0bef663ca181b38f"
        }
      ]
    }
  ]
}
